package ru.sberbank.sdcb.k7m.core.pack

object Main extends BaseMainClass{

	override def run(params: Map[String, String], config: Config): Unit = {

			val CRM_STG_ADDR = new BEN_CRM.CRM_STG.CRM_STG_ADDR(config)
			val processLogger = new ProcessLogger(CRM_STG_ADDR.spark, config, "UL") // processName- наименование процесса,
			processLogger.logStartProcess()

			CRM_STG_ADDR.save()
			val CRM_STG_CUST = new BEN_CRM.CRM_STG.CRM_STG_CUST(config)
			CRM_STG_CUST.save()
			val CRM_STG_DOC = new BEN_CRM.CRM_STG.CRM_STG_DOC(config)
			CRM_STG_DOC.save()

			val CRM_DDS_BEN_SHR_CRM = new BEN_CRM.CRM_DDS.CRM_DDS_BEN_SHR_CRM(config)
			CRM_DDS_BEN_SHR_CRM.save()
			val INN_ENRICH = new BEN_CRM.CRM_DDS.INN_ENRICH(config)
			INN_ENRICH.create()

			val Stg_UL_step1 = new STG.UL.Stg_UL_Rosstat(config)
			Stg_UL_step1.save()
			val Stg_UL_step2 = new STG.UL.Stg_UL_Egrul(config)
			Stg_UL_step2.save()
			val Stg_UL_step3 = new STG.UL.Stg_UL(config)
			Stg_UL_step3.save()
			val Stg_fnd_eg = new STG.FND_EG.Stg_fnd_eg(config)
			Stg_fnd_eg.save()
			val Stg_fnd_rs_step1 = new STG.FND_RS.Stg_fnd_rs_T1(config)
			Stg_fnd_rs_step1.save()
			val Stg_fnd_rs_step2 = new STG.FND_RS.Stg_fnd_rs_T2(config)
			Stg_fnd_rs_step2.save()
			val Stg_fnd_rs_step3 = new STG.FND_RS.Stg_fnd_rs(config)
			Stg_fnd_rs_step3.save()
			val Stg_shr_step1 = new STG.SHR.Stg_shr_T1(config)
			Stg_shr_step1.save()
			val Stg_shr_step2 = new STG.SHR.Stg_shr(config)
			Stg_shr_step2.save()
			val Stg_exec = new STG.EXEC.Stg_exec(config)
			Stg_exec.save()
			val Stg_tr_prsn = new STG.TR_PRSN.STG_tr_prsn(config)
			Stg_tr_prsn.save()
			val Stg_dir_brd = new STG.DIR_BRD.Stg_dir_brd(config)
			Stg_dir_brd.save()
			val Stg_ko_lst = new STG.KO_LST.STG_KO_Lst(config)
			Stg_ko_lst.save()
			val Stg_appl_step1 = new STG.APPL.Stg_appl_T0_clean_pass(config)
			Stg_appl_step1.save()
			val Stg_appl_step2 = new STG.APPL.Stg_appl_T0_restored(config)
			Stg_appl_step2.save()
			val Stg_appl_step3 = new STG.APPL.Stg_appl_T1(config)
			Stg_appl_step3.save()
			val Stg_appl_step4 = new STG.APPL.Stg_appl_T2(config)
			Stg_appl_step4.save()
			val Stg_appl_step5 = new STG.APPL.Stg_appl(config)
			Stg_appl_step5.save()
			val Stg_rel = new STG.REL.STG_rel(config)
			Stg_rel.save()
			val Stg_ip = new STG.IP.STG_ip(config)
			Stg_ip.save()

			val PRDDS1_fnd_eg = new PRDDS1.FND_EG.PRDDS1_fnd_eg(config)
			PRDDS1_fnd_eg.save()
			val PRDDS1_fnd_rs = new PRDDS1.FND_RS.PRDDS1_fnd_rs(config)
			PRDDS1_fnd_rs.save()

			val PRDDS2_fnd = new PRDDS2.FND.PRDDS2_fnd(config)
			PRDDS2_fnd.save()
			val PRDDS2_rel = new PRDDS2.REL.PRDDS2_rel(config)
			PRDDS2_rel.create()

			val DDS_ownr = new DDS.OWNR.DDS_ownr(config)
			DDS_ownr.save()
			val DDS_exec = new DDS.EXEC.DDS_exec(config)
			DDS_exec.save()
			val DDS_dir_brd = new DDS.DIR_BRD.DDS_dir_brd(config)
			DDS_dir_brd.save()
			val DDS_rel_step1 = new DDS.REL.DDS_rel_TX(config)
			DDS_rel_step1.save()
			val DDS_rel_step2 = new DDS.REL.DDS_rel_TX2(config)
			DDS_rel_step2.save()
			val DDS_rel_step3 = new DDS.REL.DDS_rel(config)
			DDS_rel_step3.save()
			val DDS_ko_list = new DDS.KO_LIST.DDS_ko_list(config)
			DDS_ko_list.save()

			val PRMTR1_ownr_rec = new PRMTR1.OWNR_REC.PRMTR1_ownr_rec(config)
			PRMTR1_ownr_rec.create()
			val PRMTR1_dir_aggr = new PRMTR1.DIR_AGGR.PRMTR1_dir_aggr(config)
			PRMTR1_dir_aggr.save()
			val PRTMR1_exec_aggr = new PRMTR1.EXEC_AGGR.PRMTR1_exec_aggr(config)
			PRTMR1_exec_aggr.save()
			val PRMTR1_ben_crm = new PRMTR1.BEN_CRM.PRMTR1_ben_crm(config)
			PRMTR1_ben_crm.save()
			val PRMTR1_ben_crm_cruel = new PRMTR1.BEN_CRM.PRMTR1_ben_crm_cruel(config)
			PRMTR1_ben_crm_cruel.save()

			val PRMTR2_ownr_res_t1 = new PRMTR2.OWNR_RES.PRMTR2_ownr_res_t1(config)
			PRMTR2_ownr_res_t1.save()
			val PRMTR2_ownr_res_t2 = new PRMTR2.OWNR_RES.PRMTR2_ownr_res_t2(config)
			PRMTR2_ownr_res_t2.save()
			val PRMTR2_ownr_res_t3 = new PRMTR2.OWNR_RES.PRMTR2_ownr_res_t3(config)
			PRMTR2_ownr_res_t3.save()

			val PRMTR3_ownr_ul = new PRMTR3.OWNR_UL.PRMTR3_ownr_ul(config)
			PRMTR3_ownr_ul.save()
			val PRMTR3_ownr_fl = new PRMTR3.OWNR_FL.PRMTR3_ownr_fl(config)
			PRMTR3_ownr_fl.save()

			val PRMTR4_bg_ownr = new PRMTR4.BG_OWNR.PRMTR4_bg_ownr(config)
			PRMTR4_bg_ownr.save()
			val PRMTR4_bh_ownr = new PRMTR4.BH_OWNR.PRMTR_bh_ownr(config)
			PRMTR4_bh_ownr.save()
			val PRMTR4_dir_mtch = new PRMTR4.DIR_MTCH.PRMTR4_dir_mtch(config)
			PRMTR4_dir_mtch.save()
			val PRMTR4_exec_mtch = new PRMTR4.EXEC_MTCH.PRMTR4_exec_mtch(config)
			PRMTR4_exec_mtch.save()
			val PRMTR4_extpownr = new PRMTR4.EXTPOWNR.PRMTR4_extpownr(config)
			PRMTR4_extpownr.save()
			val PRMTR4_ben_crm = new PRMTR4.BENCRM_EX.PRMTR4_bencrm_ex(config)
			PRMTR4_ben_crm.save()

			val MRT1_CRTA_5_1_1 = new MRT1.CRTA_5_1_1.MRT1_CRTA_5_1_1(config)
			MRT1_CRTA_5_1_1.save()
			val MRT1_CRTA_5_1_4 = new MRT1.CRTA_5_1_4.MRT1_CRTA_5_1_4(config)
			MRT1_CRTA_5_1_4.save()
			val MRT1_CRTA_5_1_4g = new MRT1.CRTA_5_1_4.MRT1_CRTA_5_1_4g(config)
			MRT1_CRTA_5_1_4g.append()
			val MRT1_CRTA_5_1_4sd = new MRT1.CRTA_5_1_4.MRT1_CRTA_5_1_4_sd(config)
			MRT1_CRTA_5_1_4sd.append()
			val MRT1_CRTA_5_1_5 = new MRT1.CRTA_5_1_5.MRT1_CRTA_5_1_5(config)
			MRT1_CRTA_5_1_5.save()
			val MRT1_CRTA_5_1_5g = new MRT1.CRTA_5_1_5.MRT1_CRTA_5_1_5g(config)
			MRT1_CRTA_5_1_5g.append()
			val MRT1_CRTA_5_1_6 = new MRT1.CRTA_5_1_6.MRT1_CRTA_5_1_6(config)
			MRT1_CRTA_5_1_6.create()
			val MRT1_CRTA_5_1_7_T0 = new MRT1.CRTA_5_1_7.MRT1_CRTA_5_1_7_T0(config)
			MRT1_CRTA_5_1_7_T0.save()
			val MRT1_CRTA_5_1_7 = new MRT1.CRTA_5_1_7.MRT1_CRTA_5_1_7(config)
			MRT1_CRTA_5_1_7.create()
			val MRT1_CRTA_5_1_7ben = new MRT1.CRTA_5_1_7ben.MRT1_CRTA_5_1_7ben(config)
			MRT1_CRTA_5_1_7ben.create()
			val MRT1_CRTA_5_1_8_T1 = new MRT1.CRTA_5_1_8.MRT1_CRTA_5_1_8_T1(config)
			MRT1_CRTA_5_1_8_T1.save()
			val MRT1_CRTA_5_1_8_T3 = new MRT1.CRTA_5_1_8.MRT1_CRTA_5_1_8_T3(config)
			MRT1_CRTA_5_1_8_T3.save()
			val MRT1_CRTA_5_1_8_T5 = new MRT1.CRTA_5_1_8.MRT1_CRTA_5_1_8_T5(config)
			MRT1_CRTA_5_1_8_T5.save()
			val MRT1_CRTA_5_1_8 = new MRT1.CRTA_5_1_8.MRT1_CRTA_5_1_8(config)
			MRT1_CRTA_5_1_8.save()
			val MRT1_CRTA_5_1_7ip = new MRT1.CRTA_5_1_7ip.MRT1_CRTA_5_1_7ip(config)
			MRT1_CRTA_5_1_7ip.save()
			val MRT1_CRTA_5_1_9 = new MRT1.CRTA_5_1_9.MRT1_CRTA_5_1_9(config)
			MRT1_CRTA_5_1_9.save()

			val MRT2_GSL_ALL = new MRT2.MRT2_GSL_ALL(config)
			MRT2_GSL_ALL.save()

		  val MRT3_GSL_FINAL = new MRT3.MRT3_GSL_FINAL(config)
		  MRT3_GSL_FINAL.save()
		processLogger.logEndProcess()
	}
}

